import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const resources = {
  en: { translation: { app_name: 'LBMA GOLD', home: 'Home', package_gold: 'Package Gold', transaction: 'Transaction', profile: 'Profile', login: 'Login', register: 'Register', email: 'Email', password: 'Password', forgot_password: 'Forgot Password?', dont_have_account: "Don't have an account?", have_account: 'Already have an account?', login_now: 'Login now', register_now: 'Register now', terms_agree: 'By Continuing you agree to the', terms_service: 'Terms of Service', privacy_policy: 'Privacy Policy', and: 'and', deposit: 'Deposit', withdraw: 'Withdraw', withdrawals: 'withdrawals', deposit_history: 'Deposit history', withdrawal_history: 'withdrawal history', my_wallet: 'MY WALLET', security_settings: 'Security Settings', personal_center: 'Personal center', system_functions: 'System functions', regarding_data: 'Regarding data', about: 'About', qa: 'Q&A', tc: 'T&C', language: 'Language', customer_service: 'Customer service', log_out: 'Log out', invite_code: 'Invite Code', gold_price_quotes: 'GOLD PRICE QUOTES', level: 'LEVEL', current_level: 'current level', next_level_away: 'next level away', commission: 'Commission', min: 'Min', max: 'Max', upgrade_now: 'Upgrade now', history: 'History', top_up: 'Top up', submit: 'Submit', cancel: 'Cancel', confirm: 'Confirm', loading: 'Loading...', success: 'Success', error: 'Error', no_data: 'No data', copy: 'Copy', copied: 'Copied', all: 'All', order_no: 'Order No', amount: 'Amount', status: 'Status', date: 'Date', action: 'Action', detail: 'Detail', team_report: 'Team Report', invite_friends: 'Invite Friends', convert: 'Convert', usdt_convert: 'USDT Convert', realname: 'Real Name Verification', bank: 'Bank Card', password_manage: 'Change Password', withdraw_password: 'Withdraw Password', service: 'Service', shop: 'Shop', order: 'Order', transaction_logs: 'Transaction Logs', account: 'Account' } },
  zh: { translation: { app_name: 'LBMA GOLD', home: '首页', package_gold: '套餐黄金', transaction: '交易记录', profile: '个人中心', login: '登录', register: '注册', email: '邮箱', password: '密码', forgot_password: '忘记密码？', dont_have_account: '还没有账号？', have_account: '已有账号？', login_now: '立即登录', register_now: '立即注册', terms_agree: '继续即表示您同意', terms_service: '服务条款', privacy_policy: '隐私政策', and: '和', deposit: '充值', withdraw: '提现', withdrawals: '提现', deposit_history: '充值记录', withdrawal_history: '提现记录', my_wallet: '我的钱包', security_settings: '安全设置', personal_center: '个人中心', system_functions: '系统功能', regarding_data: '相关数据', about: '关于', qa: '常见问题', tc: '条款条件', language: '语言', customer_service: '客服', log_out: '退出登录', invite_code: '邀请码', gold_price_quotes: '黄金报价', level: '等级', current_level: '当前等级', next_level_away: '距离下一级', commission: '佣金', min: '最低', max: '最高', upgrade_now: '立即升级', history: '历史记录', top_up: '充值', submit: '提交', cancel: '取消', confirm: '确认', loading: '加载中...', success: '成功', error: '错误', no_data: '暂无数据', copy: '复制', copied: '已复制', all: '全部', order_no: '订单号', amount: '金额', status: '状态', date: '日期', action: '操作', detail: '详情', team_report: '团队报表', invite_friends: '邀请好友', convert: '兑换', usdt_convert: 'USDT兑换', realname: '实名认证', bank: '银行卡', password_manage: '修改密码', withdraw_password: '提现密码', service: '客服', shop: '商城', order: '订单', transaction_logs: '交易记录', account: '账户' } },
  ar: { translation: { app_name: 'LBMA GOLD', home: 'الرئيسية', package_gold: 'ذهب الباقة', transaction: 'المعاملات', profile: 'الملف الشخصي', login: 'تسجيل الدخول', register: 'تسجيل', email: 'البريد الإلكتروني', password: 'كلمة المرور', forgot_password: 'نسيت كلمة المرور؟', dont_have_account: 'ليس لديك حساب؟', have_account: 'لديك حساب؟', login_now: 'تسجيل الدخول الآن', register_now: 'سجل الآن', terms_agree: 'بالمتابعة أنت توافق على', terms_service: 'شروط الخدمة', privacy_policy: 'سياسة الخصوصية', and: 'و', deposit: 'إيداع', withdraw: 'سحب', withdrawals: 'سحوبات', deposit_history: 'سجل الإيداع', withdrawal_history: 'سجل السحب', my_wallet: 'محفظتي', security_settings: 'إعدادات الأمان', personal_center: 'المركز الشخصي', system_functions: 'وظائف النظام', regarding_data: 'بيانات', about: 'حول', qa: 'الأسئلة الشائعة', tc: 'الشروط والأحكام', language: 'اللغة', customer_service: 'خدمة العملاء', log_out: 'تسجيل الخروج', invite_code: 'كود الدعوة', gold_price_quotes: 'أسعار الذهب', level: 'المستوى', current_level: 'المستوى الحالي', next_level_away: 'المسافة للمستوى التالي', commission: 'العمولة', min: 'الأدنى', max: 'الأقصى', upgrade_now: 'ترقية الآن', history: 'السجل', top_up: 'شحن', submit: 'إرسال', cancel: 'إلغاء', confirm: 'تأكيد', loading: 'جاري التحميل...', success: 'نجاح', error: 'خطأ', no_data: 'لا توجد بيانات', copy: 'نسخ', copied: 'تم النسخ', all: 'الكل', order_no: 'رقم الطلب', amount: 'المبلغ', status: 'الحالة', date: 'التاريخ', action: 'إجراء', detail: 'تفاصيل', team_report: 'تقرير الفريق', invite_friends: 'دعوة الأصدقاء', convert: 'تحويل', usdt_convert: 'تحويل USDT', realname: 'التحقق بالاسم الحقيقي', bank: 'بطاقة مصرفية', password_manage: 'تغيير كلمة المرور', withdraw_password: 'كلمة مرور السحب', service: 'خدمة العملاء', shop: 'متجر', order: 'طلب', transaction_logs: 'سجلات المعاملات', account: 'حساب' } },
  es: { translation: { app_name: 'LBMA GOLD', home: 'Inicio', package_gold: 'Oro Paquete', transaction: 'Transacciones', profile: 'Perfil', login: 'Iniciar sesión', register: 'Registro', email: 'Correo', password: 'Contraseña', forgot_password: '¿Olvidaste tu contraseña?', dont_have_account: '¿No tienes cuenta?', have_account: '¿Ya tienes cuenta?', login_now: 'Inicia sesión ahora', register_now: 'Regístrate ahora', terms_agree: 'Al continuar aceptas el', terms_service: 'Términos de Servicio', privacy_policy: 'Política de Privacidad', and: 'y', deposit: 'Depósito', withdraw: 'Retirar', withdrawals: 'Retiros', deposit_history: 'Historial de Depósitos', withdrawal_history: 'Historial de Retiros', my_wallet: 'MI BILLETERA', security_settings: 'Configuración de Seguridad', personal_center: 'Centro Personal', system_functions: 'Funciones del Sistema', regarding_data: 'Datos', about: 'Acerca de', qa: 'Preguntas Frecuentes', tc: 'Términos y Condiciones', language: 'Idioma', customer_service: 'Servicio al Cliente', log_out: 'Cerrar Sesión', invite_code: 'Código de Invitación', gold_price_quotes: 'PRECIOS DEL ORO', level: 'NIVEL', current_level: 'nivel actual', next_level_away: 'siguiente nivel', commission: 'Comisión', min: 'Mín', max: 'Máx', upgrade_now: 'Mejorar ahora', history: 'Historial', top_up: 'Recargar', submit: 'Enviar', cancel: 'Cancelar', confirm: 'Confirmar', loading: 'Cargando...', success: 'Éxito', error: 'Error', no_data: 'Sin datos', copy: 'Copiar', copied: 'Copiado', all: 'Todo', order_no: 'Pedido No', amount: 'Monto', status: 'Estado', date: 'Fecha', action: 'Acción', detail: 'Detalle', team_report: 'Informe de Equipo', invite_friends: 'Invitar Amigos', convert: 'Convertir', usdt_convert: 'Convertir USDT', realname: 'Verificación de Nombre Real', bank: 'Tarjeta Bancaria', password_manage: 'Cambiar Contraseña', withdraw_password: 'Contraseña de Retiro', service: 'Servicio', shop: 'Tienda', order: 'Pedido', transaction_logs: 'Registros de Transacciones', account: 'Cuenta' } },
  pt: { translation: { app_name: 'LBMA GOLD', home: 'Início', package_gold: 'Pacote Ouro', transaction: 'Transações', profile: 'Perfil', login: 'Entrar', register: 'Registrar', email: 'Email', password: 'Senha', forgot_password: 'Esqueceu a senha?', dont_have_account: 'Não tem conta?', have_account: 'Já tem conta?', login_now: 'Entrar agora', register_now: 'Registrar agora', terms_agree: 'Ao continuar você concorda com os', terms_service: 'Termos de Serviço', privacy_policy: 'Política de Privacidade', and: 'e', deposit: 'Depósito', withdraw: 'Sacar', withdrawals: 'Saques', deposit_history: 'Histórico de Depósitos', withdrawal_history: 'Histórico de Saques', my_wallet: 'MINHA CARTEIRA', security_settings: 'Configurações de Segurança', personal_center: 'Centro Pessoal', system_functions: 'Funções do Sistema', regarding_data: 'Dados', about: 'Sobre', qa: 'Perguntas Frequentes', tc: 'Termos e Condições', language: 'Idioma', customer_service: 'Atendimento ao Cliente', log_out: 'Sair', invite_code: 'Código de Convite', gold_price_quotes: 'COTAÇÕES DE OURO', level: 'NÍVEL', current_level: 'nível atual', next_level_away: 'próximo nível', commission: 'Comissão', min: 'Mín', max: 'Máx', upgrade_now: 'Melhorar agora', history: 'Histórico', top_up: 'Recarregar', submit: 'Enviar', cancel: 'Cancelar', confirm: 'Confirmar', loading: 'Carregando...', success: 'Sucesso', error: 'Erro', no_data: 'Sem dados', copy: 'Copiar', copied: 'Copiado', all: 'Tudo', order_no: 'Pedido No', amount: 'Valor', status: 'Status', date: 'Data', action: 'Ação', detail: 'Detalhe', team_report: 'Relatório de Equipe', invite_friends: 'Convidar Amigos', convert: 'Converter', usdt_convert: 'Converter USDT', realname: 'Verificação de Nome Real', bank: 'Cartão Bancário', password_manage: 'Alterar Senha', withdraw_password: 'Senha de Saque', service: 'Serviço', shop: 'Loja', order: 'Pedido', transaction_logs: 'Registros de Transações', account: 'Conta' } },
  fr: { translation: { app_name: 'LBMA GOLD', home: 'Accueil', package_gold: 'Or Package', transaction: 'Transactions', profile: 'Profil', login: 'Connexion', register: 'Inscription', email: 'Email', password: 'Mot de passe', forgot_password: 'Mot de passe oublié?', dont_have_account: "Vous n'avez pas de compte?", have_account: 'Vous avez déjà un compte?', login_now: 'Connectez-vous maintenant', register_now: 'Inscrivez maintenant', terms_agree: 'En continuant vous acceptez les', terms_service: "Conditions d'utilisation", privacy_policy: 'Politique de confidentialité', and: 'et', deposit: 'Dépôt', withdraw: 'Retrait', withdrawals: 'Retraits', deposit_history: 'Historique des dépôts', withdrawal_history: 'Historique des retraits', my_wallet: 'MON PORTEFEUILLE', security_settings: 'Paramètres de sécurité', personal_center: 'Espace personnel', system_functions: 'Fonctions système', regarding_data: 'Données', about: 'À propos', qa: 'FAQ', tc: 'CGV', language: 'Langue', customer_service: 'Service client', log_out: 'Déconnexion', invite_code: "Code d'invitation", gold_price_quotes: "COURS DE L'OR", level: 'NIVEAU', current_level: 'niveau actuel', next_level_away: 'niveau suivant', commission: 'Commission', min: 'Min', max: 'Max', upgrade_now: 'Améliorer maintenant', history: 'Historique', top_up: 'Recharger', submit: 'Soumettre', cancel: 'Annuler', confirm: 'Confirmer', loading: 'Chargement...', success: 'Succès', error: 'Erreur', no_data: 'Pas de données', copy: 'Copier', copied: 'Copié', all: 'Tout', order_no: 'Commande N°', amount: 'Montant', status: 'Statut', date: 'Date', action: 'Action', detail: 'Détail', team_report: "Rapport d'équipe", invite_friends: 'Inviter des amis', convert: 'Convertir', usdt_convert: 'Convertir USDT', realname: 'Vérification du nom réel', bank: 'Carte bancaire', password_manage: 'Changer le mot de passe', withdraw_password: 'Mot de passe de retrait', service: 'Service', shop: 'Boutique', order: 'Commande', transaction_logs: 'Journaux de transactions', account: 'Compte' } },
  de: { translation: { app_name: 'LBMA GOLD', home: 'Startseite', package_gold: 'Gold Paket', transaction: 'Transaktionen', profile: 'Profil', login: 'Anmelden', register: 'Registrieren', email: 'E-Mail', password: 'Passwort', forgot_password: 'Passwort vergessen?', dont_have_account: 'Kein Konto?', have_account: 'Schon ein Konto?', login_now: 'Jetzt anmelden', register_now: 'Jetzt registrieren', terms_agree: 'Mit der Nutzung akzeptieren Sie die', terms_service: 'Nutzungsbedingungen', privacy_policy: 'Datenschutzrichtlinie', and: 'und', deposit: 'Einzahlung', withdraw: 'Auszahlung', withdrawals: 'Auszahlungen', deposit_history: 'Einzahlungsverlauf', withdrawal_history: 'Auszahlungsverlauf', my_wallet: 'MEINE GELDBÖRSE', security_settings: 'Sicherheitseinstellungen', personal_center: 'Persönlicher Bereich', system_functions: 'Systemfunktionen', regarding_data: 'Daten', about: 'Über', qa: 'FAQ', tc: 'AGB', language: 'Sprache', customer_service: 'Kundenservice', log_out: 'Abmelden', invite_code: 'Einladungscode', gold_price_quotes: 'GOLDPREISE', level: 'LEVEL', current_level: 'aktuelles Level', next_level_away: 'nächstes Level', commission: 'Provision', min: 'Min', max: 'Max', upgrade_now: 'Jetzt upgraden', history: 'Verlauf', top_up: 'Aufladen', submit: 'Absenden', cancel: 'Abbrechen', confirm: 'Bestätigen', loading: 'Lädt...', success: 'Erfolg', error: 'Fehler', no_data: 'Keine Daten', copy: 'Kopieren', copied: 'Kopiert', all: 'Alle', order_no: 'Bestellnummer', amount: 'Betrag', status: 'Status', date: 'Datum', action: 'Aktion', detail: 'Detail', team_report: 'Team-Bericht', invite_friends: 'Freunde einladen', convert: 'Konvertieren', usdt_convert: 'USDT Konvertieren', realname: 'Echtname-Verifizierung', bank: 'Bankkarte', password_manage: 'Passwort ändern', withdraw_password: 'Auszahlungspasswort', service: 'Service', shop: 'Shop', order: 'Bestellung', transaction_logs: 'Transaktionsprotokolle', account: 'Konto' } },
};

const savedLang = localStorage.getItem('i18nextLng') || 'en';

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    lng: savedLang,
    fallbackLng: 'en',
    interpolation: { escapeValue: false },
    detection: { order: ['localStorage', 'navigator'], caches: ['localStorage'] },
  });

export default i18n;
