import DOMPurify from 'dompurify';
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { getPrivacyPolicy } from '../api';

const CONTENT = `
<p><strong>PRIVACY POLICY</strong></p>
<p>This Privacy Policy describes how LBMA GOLD collects, uses, and protects your information when you use our platform.</p>
<p>&nbsp;</p>
<p><strong>1. Information We Collect</strong></p>
<p>Account information you provide at registration (email address), profile details you add (real name, KYC documents), and transaction records (deposits, withdrawals, orders) generated by your activity. We also collect technical data such as IP address and browser type for security purposes.</p>
<p>&nbsp;</p>
<p><strong>2. How We Use Information</strong></p>
<p>To operate your account, process transactions, verify identity (KYC), prevent fraud, comply with legal obligations, and provide customer support.</p>
<p>&nbsp;</p>
<p><strong>3. Data Security</strong></p>
<p>Passwords are hashed. Sensitive operations require additional authentication (withdrawal password, admin two-factor). Access to personal data is restricted to authorized personnel. Despite these measures, no system is perfectly secure.</p>
<p>&nbsp;</p>
<p><strong>4. Data Retention</strong></p>
<p>We retain transaction records for the period necessary to fulfill the purposes outlined here and to comply with legal or regulatory requirements.</p>
<p>&nbsp;</p>
<p><strong>5. Your Rights</strong></p>
<p>You may request access to or correction of your personal information by contacting support. We will respond within a reasonable timeframe.</p>
<p>&nbsp;</p>
<p><strong>6. Third Parties</strong></p>
<p>We do not sell your personal information. Service providers (e.g., blockchain networks for deposits) process data only as necessary to deliver the service.</p>
<p>&nbsp;</p>
<p><strong>7. Changes</strong></p>
<p>We may update this policy from time to time. Material changes will be notified through the platform.</p>
<p>&nbsp;</p>
<p>© LBMA GOLD. All rights reserved.</p>
`;

export default function PrivacyPolicy() {
  const nav = useNavigate();
  const [html, setHtml] = useState(CONTENT);
  useEffect(() => {
    getPrivacyPolicy().then(r => { const c = r.data?.data?.content; if (c) setHtml(c); }).catch(() => {});
  }, []);
  return (
    <div className="min-h-screen max-w-[400px] mx-auto bg-[#0a0e1a] pb-10">
      <div className="flex items-center px-4 pt-3 pb-4">
        <span className="text-white cursor-pointer text-lg" onClick={() => nav(-1)}><i className="fa-solid fa-chevron-left"></i></span>
        <span className="flex-1 text-center text-white font-bold text-base">Privacy Policy</span>
        <span className="w-[18px]"></span>
      </div>
      <div className="px-4 mt-2">
        <div className="bg-[#0a1a3a] rounded-xl p-4">
          <div className="text-gray-300 text-sm leading-relaxed" dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(html) }} />
        </div>
      </div>
    </div>
  );
}
